todos = open('todos.txt', 'a')
print('На поверхности слишком ярко, слишком легко.', file = todos)
print('Я тоскую по глубинам, где водная толща давит на тело', file = todos)
print('и в сумраке подводного мира угадываются неясные огоньки.', file = todos)
todos.close()